import { JobCard } from './job-card/job-card.types';

export const JOBS_DATA: JobCard[] = [
  {
    id: 1,
    category: 'delivery',
    name: 'Забрать документы и доставить в центр',
    location: 'Гомель',
    deadline: 'Сегодня до 18:00',
    salary: 70,
    currency: '$',
    paymentType: 'fix',
    responds: 5,
  },
  {
    id: 2,
    category: 'repair',
    name: 'Установить две потолочные лампы в квартире',
    location: 'Жлобин',
    deadline: '27.04.2025 в 12:00',
    salary: 120,
    currency: 'BYN',
    paymentType: 'fix',
    responds: 2,
  },
  {
    id: 3,
    category: 'design',
    name: 'Редизайн лендинга для локальной пекарни',
    location: 'Удаленно',
    deadline: 'Срок 3 дня',
    salary: 450,
    currency: '$',
    paymentType: 'fix',
    responds: 12,
  },
  {
    id: 4,
    category: 'tutoring',
    name: 'Репетитор по математике для 10 класса',
    location: 'Чикаго, IL',
    deadline: '2 занятия на этой неделе',
    salary: 45,
    currency: '$',
    paymentType: 'hour',
    responds: 3,
  },
  {
    id: 5,
    category: 'repair',
    name: 'Покрасить комнату и заделать трещины в стене',
    location: 'Финикс, AZ',
    deadline: 'В эти выходные',
    salary: 320,
    currency: '$',
    paymentType: 'fix',
    responds: 9,
  },
  {
    id: 6,
    category: 'delivery',
    name: 'Доставка мебели из магазина домой',
    location: 'Сиэтл, WA',
    deadline: 'Пятница 13:00',
    salary: 95,
    currency: '$',
    paymentType: 'fix',
    responds: 6,
  },
];

export const FILTER_OPTIONS = [
  { value: 'all' as const, label: 'Все' },
  { value: 'delivery' as const, label: 'Доставка' },
  { value: 'repair' as const, label: 'Ремонт' },
  { value: 'design' as const, label: 'Дизайн' },
  { value: 'tutoring' as const, label: 'Обучение' },
];
